name: Tests

on: [push, workflow_dispatch]

jobs:
  test-switch:
    runs-on: ubuntu-latest
    services:
      rabbit:
        image: rabbitmq:latest
        ports:
          - 5672:5672
      redis:
        image: redis:latest
        ports:
          - 6379:6379
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r src/services/switch/requirements.txt httpx
      - name: Test
        run: |
          python -m unittest \
            src/services/switch/tests.py \
            src/services/observer/tests.py \
            src/services/manager/tests.py
